ame: Blue Iris Books website
baseurl:
url: 
permalink: pretty
title: Blue Iris Books
description: Blue Iris Books is an independent publishing company. We publish novels, memoirs, essays, and poetry.
